version: "2"

linters:
  enable:
    - bodyclose
    - errcheck
    - errorlint
    - govet
    - ineffassign
    - noctx
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - unused
  settings:
    errcheck:
      exclude-functions:
        - (io.Closer).Close
        - (*os.File).Close
        - (*os.Root).Close
        - (*archive/zip.ReadCloser).Close
        - (io.ReadCloser).Close
